language: node_js
sudo: false
notifications:
  irc: "irc.blitzed.org#stonecypher-builds"
  recipients:
    - stonecypher@gmail.com
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script: npm install
script: npm test